# Generated by Django 5.0.4 on 2024-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_commonuser_resident_condominium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
