# Generated by Django 5.0.4 on 2024-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_commonuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='condo_me/users/%Y/%m/%d/'),
        ),
    ]
