services:
  psql: 
    image: postgres:17-alpine
    container_name: postgres_container
    networks:
      - django_network
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
networks:
  django_network:
    driver: bridge