services:
  condo_me_web:
    container_name: condo_me_web_container
    build:
      context: . # where Dockerfile is located
      dockerfile: Dockerfile
      args: 
        UID: 1000
        GID: 1000
    image: condo_me_web:latest
    ports:
      - 8000:8000
    volumes: 
      - ./src:/app/src
      - ./data/web/static:/app/data/web/static/
      - ./data/web/media:/app/data/web/media/
    user: "django_user"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONPATH=/app/src:/app
    env_file:
      - ./.env
    depends_on:
      - psql
    working_dir: /app/src
    
  psql:
    container_name: psql_container
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
