# Generated by Django 5.0.4 on 2024-08-12 13:23

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ number mask must be XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}-\\d{2}$')])),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborwood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Write details about your condominium.')),
                ('image', models.ImageField(blank=True, upload_to='condo_me/condominiums/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Write details and rules about this Common Area.')),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('whole_day', models.BooleanField(verbose_name='Must be a whole day reservation?')),
                ('paid_area', models.BooleanField(verbose_name='User have to pay for use?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='In Brazilian Reais', max_digits=5, null=True, verbose_name='Price')),
                ('minimum_using_minutes', models.IntegerField(blank=True, choices=[(30, '30'), (60, '60')], help_text='Leave blank in case of whole day use.', null=True, verbose_name='Minimum using time in minutes')),
                ('maximum_using_fraction', models.IntegerField(blank=True, help_text='Leave blank in case of whole day use.', null=True, verbose_name='Choose an integer. It will be multiplied by minimum             using minutes (above) in order to obtain maximum using time                 (bellow)')),
                ('maximum_using_time', models.IntegerField(blank=True, help_text='It will be blank in case of whole day use.', null=True, verbose_name='Maximum using time (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='condo_me/common_areas/%Y/%m/%d/')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='condo.condominium')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Block', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='condo.condominium')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_or_name', models.CharField(max_length=20, verbose_name='Number (or name)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='condo.block')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='condo.condominium')),
            ],
            options={
                'ordering': ['number_or_name', 'block'],
            },
        ),
    ]
