# Generated by Django 5.1 on 2024-12-31 13:04

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Condominium",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("address1", models.CharField(max_length=150)),
                ("address2", models.CharField(default="", max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=30)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "description",
                    models.TextField(help_text="Write details about your condominium."),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="condo_me/condominiums/%Y/%m/%d/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(
                        help_text="Write details and rules about this Common Area."
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "whole_day",
                    models.BooleanField(
                        verbose_name="Must be a whole day reservation?"
                    ),
                ),
                (
                    "paid_area",
                    models.BooleanField(verbose_name="User have to pay for use?"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In Brazilian Reais",
                        max_digits=5,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "minimum_using_minutes",
                    models.IntegerField(
                        blank=True,
                        choices=[(30, "30"), (60, "60")],
                        help_text="Leave blank in case of whole day use.",
                        null=True,
                        verbose_name="Minimum using time in minutes",
                    ),
                ),
                (
                    "maximum_using_fraction",
                    models.IntegerField(
                        blank=True,
                        help_text="Leave blank in case of whole day use.",
                        null=True,
                        verbose_name="Choose an integer. It will be multiplied by minimum             using minutes (above) in order to obtain maximum using time                 (bellow)",
                    ),
                ),
                (
                    "maximum_using_time",
                    models.IntegerField(
                        blank=True,
                        help_text="It will be blank in case of whole day use.",
                        null=True,
                        verbose_name="Maximum using time (minutes)",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="common_areas/%Y/%m/%d/"
                    ),
                ),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_areas",
                        to="condo.condominium",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Main Block", max_length=120, unique=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Write details about this block.",
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="condo_me/blocks/%Y/%m/%d/"
                    ),
                ),
                (
                    "condominium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="condo.condominium",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number_or_name",
                    models.CharField(max_length=20, verbose_name="Number (or name)"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="condo.block",
                    ),
                ),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="condo.condominium",
                    ),
                ),
            ],
            options={
                "ordering": ["number_or_name", "block"],
            },
        ),
    ]
