# Generated by Django 5.1.5 on 2025-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonarea",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="commonarea",
            name="description",
            field=models.TextField(
                help_text="Provide the details and rules for this common area."
            ),
        ),
        migrations.AlterField(
            model_name="commonarea",
            name="paid_area",
            field=models.BooleanField(
                verbose_name="Resident must pay for using this common area?"
            ),
        ),
    ]
