# Generated by Django 5.1 on 2025-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this block",
                null=True,
                upload_to="condo_me/blocks/%Y/%m/%d/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(default="Main Block", max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("name", "condominium")},
        ),
    ]
