# Generated by Django 5.1 on 2025-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0002_alter_block_cover_alter_block_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="block",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("name", "condominium"), name="unique_block_name_per_condo"
            ),
        ),
    ]
