# Generated by Django 5.1.5 on 2025-02-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0002_alter_block_name_alter_block_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condominium",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
