# Generated by Django 5.1 on 2024-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0003_alter_condominium_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonarea',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='common_areas/%Y/%m/%d/'),
        ),
    ]
