# Generated by Django 5.1 on 2025-01-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0003_alter_block_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="block",
            name="unique_block_name_per_condo",
        ),
    ]
