# Generated by Django 5.1 on 2024-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0004_alter_commonarea_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="description",
            field=models.TextField(
                blank=True, help_text="Write details about this block.", null=True
            ),
        ),
    ]
