# Generated by Django 5.1 on 2024-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0005_block_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="name",
            field=models.CharField(default="Main Block", max_length=120, unique=True),
        ),
    ]
