# Generated by Django 5.1 on 2025-01-06 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0005_alter_block_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_blocks", models.BooleanField(default=False)),
                ("has_apartments", models.BooleanField(default=False)),
                ("has_residents", models.BooleanField(default=False)),
                ("has_common_areas", models.BooleanField(default=False)),
                (
                    "condominium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_progress",
                        to="condo.condominium",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
