# Generated by Django 5.1 on 2025-01-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0006_setupprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="setupprogress",
            name="has_condominium",
            field=models.BooleanField(default=False),
        ),
    ]
