# Generated by Django 5.1 on 2024-09-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0002_createmanagertoken_delete_purchasetoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="createmanagertoken",
            old_name="email",
            new_name="customer_email",
        ),
        migrations.RenameField(
            model_name="createmanagertoken",
            old_name="first_name",
            new_name="customer_first_name",
        ),
        migrations.RenameField(
            model_name="createmanagertoken",
            old_name="group",
            new_name="customer_group",
        ),
        migrations.RenameField(
            model_name="createmanagertoken",
            old_name="last_name",
            new_name="customer_last_name",
        ),
    ]
