# Generated by Django 5.1 on 2024-09-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_rename_createmanagertoken_registrationtoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationtoken",
            old_name="customer_email",
            new_name="register_email",
        ),
        migrations.RenameField(
            model_name="registrationtoken",
            old_name="customer_first_name",
            new_name="register_first_name",
        ),
        migrations.RenameField(
            model_name="registrationtoken",
            old_name="customer_group",
            new_name="register_group",
        ),
        migrations.RenameField(
            model_name="registrationtoken",
            old_name="customer_last_name",
            new_name="register_last_name",
        ),
    ]
