# Generated by Django 5.0.4 on 2024-07-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_people', '0002_alter_user_apartment_alter_user_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
    ]
