# Generated by Django 5.1 on 2024-09-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condo_people", "0002_remove_user_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="cover",
        ),
    ]
