# Generated by Django 5.0.4 on 2024-08-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
