# Generated by Django 5.1 on 2025-01-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0006_setupprogress"),
        ("condo_people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="condo_person",
                to="condo.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="condominium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="condo_person",
                to="condo.condominium",
            ),
        ),
    ]
