# Generated by Django 5.1 on 2024-12-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo", "0007_alter_condominium_cnpj"),
        ("condo_people", "0004_alter_user_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="condo.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="condominium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="condo.condominium",
            ),
        ),
    ]
