# Generated by Django 5.1 on 2024-12-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condo_people", "0005_alter_user_apartment_alter_user_condominium"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
