# Generated by Django 5.0.4 on 2024-05-08 13:08

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number', 'block'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Block', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('whole_day', models.BooleanField(verbose_name='Whole day Reservation applied?')),
                ('paid_area', models.BooleanField(verbose_name='User have to pay for use?')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('minimum_using_minutes', models.IntegerField(choices=[(30, '30'), (60, '60')], verbose_name='Minimum using time in minutes')),
                ('maximum_using_fraction', models.IntegerField(verbose_name='Choose an integer. It will be multiplied by minimum             using minutes in order to obtain maximum using time')),
                ('maximum_using_time', models.IntegerField()),
                ('image', models.ImageField(upload_to='condo_me/common_areas/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ number mask must be XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}-\\d{2}$')])),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborwood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='condo_me/condominiums/%Y/%m/%d/')),
            ],
        ),
    ]
