# Generated by Django 5.0.4 on 2024-04-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='residents',
            field=models.ManyToManyField(related_name='ResidentApartment', to='users.commonuser'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='condo.block'),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_areas', to='condo.condominium'),
        ),
        migrations.AddField(
            model_name='block',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='condo.condominium'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='condo.condominium'),
        ),
    ]
