# Generated by Django 5.0.4 on 2024-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='reservation.reservation'),
        ),
    ]
