# Generated by Django 5.0.4 on 2024-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0002_initial'),
        ('users', '0003_alter_commonuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='ResidentApartment', to='users.commonuser'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='image',
            field=models.ImageField(blank=True, upload_to='condo_me/condominiums/%Y/%m/%d/'),
        ),
    ]
