# Generated by Django 5.0.4 on 2024-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='reservations',
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='condo_me/common_areas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='maximum_using_fraction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choose an integer. It will be multiplied by minimum             using minutes (above) in order to obtain maximum using time                 (bellow)'),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='maximum_using_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='minimum_using_minutes',
            field=models.IntegerField(blank=True, choices=[(30, '30'), (60, '60')], null=True, verbose_name='Minimum using time in minutes'),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='whole_day',
            field=models.BooleanField(verbose_name='Must be a whole day reservation?'),
        ),
    ]
