# Generated by Django 5.0.4 on 2024-05-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0003_alter_apartment_number_alter_apartment_residents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['number', 'block']},
        ),
    ]
