# Generated by Django 5.0.4 on 2024-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0004_remove_apartment_reservations_alter_commonarea_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonarea',
            name='maximum_using_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum using time (minutes)'),
        ),
    ]
