# Generated by Django 5.0.4 on 2024-05-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reservation Date')),
                ('start_time', models.TimeField(verbose_name='Time user will start to use the common area')),
                ('end_time', models.TimeField(verbose_name='Time user will end to use the common area')),
                ('share_with_others', models.BooleanField(verbose_name='Main user may share common area with other users?')),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condo.commonarea')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condo.condominium')),
            ],
        ),
    ]
