# Generated by Django 5.0.4 on 2024-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
