# Generated by Django 5.0.4 on 2024-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Leave blank if this is a whole day use common area', null=True, verbose_name='User will end to use the common area at:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Leave blank if this is a whole day use common area', null=True, verbose_name='User will start to use the common area at:'),
        ),
    ]
